---
fields:
  - id: endpoint
    help_text: "API endpoint"
    label: Endpoint
    type: string
  - id: username
    help_text: "Username to access the API endpoint"
    label: Username
    type: string
  - id: password
    help_text: "Password to access the API endpoint"
    label: Password
    secret: true
    type: string
  - id: required_variables
    help_text: "Extra variables to be present so that the POST action will be submitted, if empty default values will be loaded (resource_id,transaction_id)"
    label: Extra variable present
    type: string
  - id: skip_empty_task_name
    help_text: "If the task doesn't have a name set then the POST action will be skipped"
    label: Skip empty task name
    type: boolean
  - id: verbose
    help_text: "Send verbose POST to API endpoint"
    label: Verbose
    type: boolean
required:
  - endpoint
  - username
  - password
